function [init] = get_init_conditions(param, t)
%CHIK_INIT_CONDITIONS Given tspan, return desired initial conditions

S_h1 = param.H0 * (param.theta1) - param.init_cumulative_infected* (param.theta1);
S_h2 = param.H0 * (param.theta1) - param.init_cumulative_infected* (param.theta2);

init = [...
    S_h1; ...
    S_h2; ...
    param.init_cumulative_infected * (param.theta1); ...
    param.init_cumulative_infected * (param.theta2); ...
    0; ...
    0; ...
    param.init_cumulative_infected * (param.theta1); ...
    param.init_cumulative_infected * (param.theta2); ...
    param.K_v; ...
    0; ...
    0];

end