function [init] = get_init_conditions2(param)
%CHIK_INIT_CONDITIONS Given tspan, return desired initial conditions

S_h2 = param.H0*param.theta2 - param.init_cumulative_infected;

init = [...
    S_h2; ...
    param.init_cumulative_infected; ...
    0; ...
    param.init_cumulative_infected; ...
    param.K_v; ...
    0; ...
    0];

end