function [init] = sir_init_conditions(param, t, total_pop)
%SIR_INIT_CONDITIONS Given tspan, return desired initial conditions

init = [...
    total_pop - param.init_infected; ...
    param.init_infected; ...
    0; ...
    param.init_infected];

end